const users = [
  {
    id: "u1",
    username: "kendrick",
    email: "kendrick@example.com",
    profile: {
      bio: "Frontend dev",
      avatarUrl: "/images/kendrick.jpg",
      location: "Addis Ababa",
      website: "https://kendrick.dev",
    },
    status: "ONLINE",
  },
  {
    id: "u2",
    username: "Bane",
    email: "bane@example.com",
    profile: {
      bio: "Backend wizard",
      avatarUrl: "/images/bane.jpg",
      location: "Paris",
      website: "https://bane.io",
    },
    status: "OFFLINE",
  },
  {
    id: "u3",
    username: "The Weeknd",
    email: "xo@example.com",
    profile: {
      bio: "Designer",
      avatarUrl: "/images/xo.jpg",
      location: "Lagos",
      website: "https://xo.design",
    },
    status: "ONLINE",
  },
  {
    id: "u4",
    username: "john_doe",
    email: "john@example.com",
    profile: {
      bio: "Full-stack developer",
      avatarUrl: "/images/john.jpg",
      location: "New York",
      website: "https://johndoe.dev",
    },
    status: "ONLINE",
  },
  {
    id: "u5",
    username: "kong_fury",
    email: "kong@example.com",
    profile: {
      bio: "Fitness enthusiast",
      avatarUrl: "/images/kong.jpg",
      location: "Tokyo",
      website: "https://kongfitness.com",
    },
    status: "OFFLINE",
  },
];

const groups = [
  {
    id: "g1",
    name: "CODERS",
    profile: { bio: "Night coders unite", avatarUrl: "/images/john.jpg" },
    ownerId: "u1",
    members: ["u1", "u2", "u3", "u4"],
    posts: [
      {
        id: "p1",
        text: "First post in CODERS group",
        userId: "u1",
        created: "2026-03-28T10:30:00Z",
        comments: [
          {
            id: "c1",
            text: "Nice work!",
            userId: "u2",
            created: "2026-03-28T11:00:00Z",
            replies: [
              {
                id: "c1-1",
                text: "Thanks!",
                userId: "u1",
                created: "2026-03-28T11:15:00Z",
              },
            ],
          },
          {
            id: "c2",
            text: "Cool project",
            userId: "u3",
            created: "2026-03-28T12:00:00Z",
            replies: [],
          },
        ],
        reactions: [
          {
            id: "r1",
            emoji: "👍",
            userId: "u2",
            created: "2026-03-28T11:05:00Z",
          },
          {
            id: "r2",
            emoji: "🚀",
            userId: "u3",
            created: "2026-03-28T12:05:00Z",
          },
          {
            id: "r3",
            emoji: "❤️",
            userId: "u4",
            created: "2026-03-28T13:00:00Z",
          },
        ],
      },
      {
        id: "p2",
        text: "Just deployed my first React app! The component-based architecture is amazing. 🚀",
        userId: "u4",
        created: "2026-03-29T09:00:00Z",
        comments: [
          {
            id: "c3",
            text: "Congrats! React is such a powerful library.",
            userId: "u1",
            created: "2026-03-29T09:30:00Z",
            replies: [],
          },
        ],
        reactions: [
          {
            id: "r4",
            emoji: "🎉",
            userId: "u1",
            created: "2026-03-29T09:15:00Z",
          },
          {
            id: "r5",
            emoji: "👍",
            userId: "u2",
            created: "2026-03-29T10:00:00Z",
          },
        ],
      },
      {
        id: "p3",
        text: "Tips for debugging Node.js applications: Use the built-in debugger, add proper logging, and always check your async/await error handling.",
        userId: "u2",
        created: "2026-03-29T14:00:00Z",
        comments: [
          {
            id: "c4",
            text: "Great tips! I also recommend using breakpoints in Chrome DevTools.",
            userId: "u3",
            created: "2026-03-29T14:30:00Z",
            replies: [
              {
                id: "c4-1",
                text: "Absolutely! The debugger statement is a game changer.",
                userId: "u2",
                created: "2026-03-29T14:45:00Z",
              },
            ],
          },
        ],
        reactions: [
          {
            id: "r6",
            emoji: "👍",
            userId: "u1",
            created: "2026-03-29T14:15:00Z",
          },
          {
            id: "r7",
            emoji: "💡",
            userId: "u4",
            created: "2026-03-29T15:00:00Z",
          },
        ],
      },
    ],
  },
  {
    id: "g2",
    name: "GYM",
    profile: { bio: "Crossfit for life!", avatarUrl: "/images/kong.jpg" },
    ownerId: "u2",
    members: ["u2", "u3", "u5"],
    posts: [
      {
        id: "p4",
        imgUrl: "/images/leg.jpg",
        text: "Workout pic",
        userId: "u2",
        created: "2026-03-28T06:00:00Z",
        comments: [
          {
            id: "c5",
            text: "Strong!",
            userId: "u1",
            created: "2026-03-28T07:00:00Z",
            replies: [],
          },
          {
            id: "c6",
            text: "Keep it up!",
            userId: "u3",
            created: "2026-03-28T08:00:00Z",
            replies: [],
          },
        ],
        reactions: [
          {
            id: "r8",
            emoji: "💪",
            userId: "u3",
            created: "2026-03-28T07:30:00Z",
          },
          {
            id: "r9",
            emoji: "🔥",
            userId: "u5",
            created: "2026-03-28T08:30:00Z",
          },
        ],
      },
      {
        id: "p5",
        text: "Morning workout done! Remember: consistency beats intensity every time. 💪",
        userId: "u5",
        created: "2026-03-29T05:30:00Z",
        comments: [
          {
            id: "c7",
            text: "So true! I try to work out at the same time every day.",
            userId: "u2",
            created: "2026-03-29T06:00:00Z",
            replies: [
              {
                id: "c7-1",
                text: "Same here! 6 AM workouts have become my favorite part of the day.",
                userId: "u5",
                created: "2026-03-29T06:15:00Z",
              },
            ],
          },
        ],
        reactions: [
          {
            id: "r10",
            emoji: "👍",
            userId: "u2",
            created: "2026-03-29T05:45:00Z",
          },
          {
            id: "r11",
            emoji: "❤️",
            userId: "u3",
            created: "2026-03-29T06:30:00Z",
          },
        ],
      },
      {
        id: "p6",
        text: "Just hit a new PR on deadlifts! 315 lbs! Hard work pays off. 🎯",
        userId: "u5",
        created: "2026-03-30T07:00:00Z",
        comments: [
          {
            id: "c8",
            text: "315 lbs is beast mode! Whats your next goal?",
            userId: "u2",
            created: "2026-03-30T07:30:00Z",
            replies: [],
          },
        ],
        reactions: [
          {
            id: "r12",
            emoji: "🏅",
            userId: "u2",
            created: "2026-03-30T07:15:00Z",
          },
          {
            id: "r13",
            emoji: "🔥",
            userId: "u3",
            created: "2026-03-30T08:00:00Z",
          },
        ],
      },
    ],
  },
  {
    id: "g3",
    name: "DESIGNERS",
    profile: { bio: "Creative minds unite", avatarUrl: "/images/xo.jpg" },
    ownerId: "u3",
    members: ["u1", "u3", "u4", "u5"],
    posts: [
      {
        id: "p7",

        text: "Just finished a new UI kit for mobile apps. What do you think? 🎨",
        userId: "u3",
        created: "2026-03-28T15:00:00Z",
        comments: [
          {
            id: "c9",
            text: "Looks amazing! Love the color palette.",
            userId: "u1",
            created: "2026-03-28T15:30:00Z",
            replies: [
              {
                id: "c9-1",
                text: "Thanks! I spent a lot of time on the gradients.",
                userId: "u3",
                created: "2026-03-28T15:45:00Z",
              },
              {
                id: "c9-2",
                text: "dope.",
                userId: "u1",
                created: "2026-03-28T15:45:00Z",
              },
            ],
          },
          {
            id: "c10",
            text: "Can you share the Figma file?",
            userId: "u4",
            created: "2026-03-28T16:00:00Z",
            replies: [],
          },
        ],
        reactions: [
          {
            id: "r14",
            emoji: "❤️",
            userId: "u1",
            created: "2026-03-28T15:15:00Z",
          },
          {
            id: "r15",
            emoji: "🎨",
            userId: "u4",
            created: "2026-03-28T16:15:00Z",
          },
          {
            id: "r16",
            emoji: "👍",
            userId: "u5",
            created: "2026-03-28T17:00:00Z",
          },
        ],
      },
      {
        id: "p8",

        text: "Design tip: Always use a grid system. It creates consistency and makes your layouts more professional.",
        userId: "u4",
        created: "2026-03-29T11:00:00Z",
        comments: [
          {
            id: "c11",
            text: "Great advice! I use 8px grid for everything.",
            userId: "u3",
            created: "2026-03-29T11:30:00Z",
            replies: [],
          },
        ],
        reactions: [
          {
            id: "r17",
            emoji: "💡",
            userId: "u3",
            created: "2026-03-29T11:15:00Z",
          },
          {
            id: "r18",
            emoji: "👍",
            userId: "u5",
            created: "2026-03-29T12:00:00Z",
          },
        ],
      },
    ],
  },
];

const notifications = [
  {
    id: "n1",
    type: "COMMENT",
    message: "Bane commented on your post",
    createdAt: "2026-03-28T11:00:00Z",
    read: false,
    senderId: "u2",
    receiverId: "u1",
    postId: "p1",
    commentId: "c1",
  },
  {
    id: "n2",
    type: "REACTION",
    message: "The Weeknd reacted to your post",
    createdAt: "2026-03-28T12:05:00Z",
    read: true,
    senderId: "u3",
    receiverId: "u1",
    postId: "p1",
    reactionId: "r2",
  },
  {
    id: "n3",
    type: "COMMENT",
    message: "kendrick commented on your post",
    createdAt: "2026-03-29T09:30:00Z",
    read: false,
    senderId: "u1",
    receiverId: "u4",
    postId: "p2",
    commentId: "c3",
  },
  {
    id: "n4",
    type: "REACTION",
    message: "kendrick reacted to your post",
    createdAt: "2026-03-29T09:15:00Z",
    read: true,
    senderId: "u1",
    receiverId: "u4",
    postId: "p2",
    reactionId: "r4",
  },
  {
    id: "n5",
    type: "COMMENT",
    message: "john_doe commented on your post",
    createdAt: "2026-03-28T07:00:00Z",
    read: false,
    senderId: "u4",
    receiverId: "u2",
    postId: "p4",
    commentId: "c5",
  },
  {
    id: "n6",
    type: "REACTION",
    message: "The Weeknd reacted to your post",
    createdAt: "2026-03-28T07:30:00Z",
    read: true,
    senderId: "u3",
    receiverId: "u2",
    postId: "p4",
    reactionId: "r8",
  },
  {
    id: "n7",
    type: "COMMENT",
    message: "Bane commented on your post",
    createdAt: "2026-03-29T06:00:00Z",
    read: false,
    senderId: "u2",
    receiverId: "u5",
    postId: "p5",
    commentId: "c7",
  },
  {
    id: "n8",
    type: "REACTION",
    message: "Bane reacted to your post",
    createdAt: "2026-03-29T05:45:00Z",
    read: true,
    senderId: "u2",
    receiverId: "u5",
    postId: "p5",
    reactionId: "r10",
  },
  {
    id: "n9",
    type: "COMMENT",
    message: "kendrick commented on your post",
    createdAt: "2026-03-28T15:30:00Z",
    read: false,
    senderId: "u1",
    receiverId: "u3",
    postId: "p7",
    commentId: "c9",
  },
  {
    id: "n10",
    type: "REACTION",
    message: "kendrick reacted to your post",
    createdAt: "2026-03-28T15:15:00Z",
    read: true,
    senderId: "u1",
    receiverId: "u3",
    postId: "p7",
    reactionId: "r14",
  },
  {
    id: "n11",
    type: "GROUP_INVITE",
    message: "You were added to CODERS group",
    createdAt: "2026-03-27T10:00:00Z",
    read: true,
    senderId: "u1",
    receiverId: "u4",
  },
  {
    id: "n12",
    type: "GROUP_INVITE",
    message: "You were added to GYM group",
    createdAt: "2026-03-27T11:00:00Z",
    read: true,
    senderId: "u2",
    receiverId: "u5",
  },
];

const privateChats = [
  {
    id: "pc1",
    text: "Hey, can you help me with the React project?",
    read: true,
    created: "2026-03-28T10:00:00Z",
    senderId: "u1",
    receiverId: "u4",
    reactions: [
      {
        id: "pcr1",
        emoji: "👍",
        userId: "u4",
        created: "2026-03-28T10:05:00Z",
      },
    ],
  },
  {
    id: "pc2",
    text: "Sure! What do you need help with?",
    read: true,
    created: "2026-03-28T10:10:00Z",
    senderId: "u4",
    receiverId: "u1",
    reactions: [],
  },
  {
    id: "pc3",
    text: "Check out this workout routine I found!",
    imgUrl: "/images/gym.jpg",
    read: false,
    created: "2026-03-29T06:00:00Z",
    senderId: "u5",
    receiverId: "u2",
    reactions: [
      {
        id: "pcr2",
        emoji: "💪",
        userId: "u2",
        created: "2026-03-29T06:15:00Z",
      },
    ],
  },
  {
    id: "pc4",
    text: "Love the new design concepts!",
    read: true,
    created: "2026-03-29T12:00:00Z",
    senderId: "u1",
    receiverId: "u3",
    reactions: [
      {
        id: "pcr3",
        emoji: "❤️",
        userId: "u3",
        created: "2026-03-29T12:05:00Z",
      },
    ],
  },
  {
    id: "pc5",
    text: "Can we schedule a design review?",
    read: false,
    created: "2026-03-30T09:00:00Z",
    senderId: "u4",
    receiverId: "u3",
    reactions: [],
  },
];

export { users, groups, notifications, privateChats };
